### PR TITLE
[tvla] Fix plotting issues with new database and metadata format

### PR DESCRIPTION
**Pull request by wettermo**
This commit fixes incompatibility of tvla plotting with the new database and metadata format.

For this, additional metadata is stored in aes, otbn, kmac and sha3 capture. Also, a new wrapper function for plotting is added to the tvla script. Finally, aes, otbn, kmac and sha3 config files are adjusted.

Further, this PR adds code to also include metadata in plots of aes specific tests.

Through this PR two tasks in https://github.com/lowRISC/ot-sca/issues/72 are addressed:
- [x] At the moment, TVLA figures contain meta-data only for general TVLA test. We should enable the same for AES specific TVLA tests.
- [x] At the moment, tvla.py cannot generate some figures if data is loaded from the new database format.

### CODE REVIEW

**Review by nasahlpa — APPROVED** [review]
Thanks for adapting all the scripts!

**Review by vrozic — APPROVED** [review]
Thanks @wettermo 
This looks good to me.
The CI failure is unrelated to this PR, so I think it can be safely merged.

**Comment by wettermo** [comment]
Thanks @nasahlpa and @vrozic for the reviews!

**Comment by wettermo** [comment]
I'm merging this PR, even though CI fails, because CI failure is unrelated to this PR.

**Pull request merged**
